name: CI

on:
  push:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2beta
      - uses: actions/setup-node@v1
        with:
          node_version: 16
      - run: npm test
